export type BodyPart = '가슴' | '등' | '어깨' | '삼두' | '이두' | '하체' | '복근' | '전완' | '전신' | '유산소';
export type Equipment = '맨몸' | '덤벨' | '바벨' | '머신' | '케이블' | '케틀벨' | '밴드' | '기타';
export type RecordType = 'weight_reps' | 'reps_only' | 'time';

export interface Exercise {
  id: string;
  name: string;
  body_part: BodyPart;
  equipment: Equipment;
  record_type: RecordType;
}

export const EXERCISE_DB: Exercise[] = [
  // ── 가슴 ─────────────────────────────────────────────────────────────────
  { id: 'c01', name: '바벨 벤치프레스',          body_part: '가슴', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'c02', name: '인클라인 바벨 벤치프레스',  body_part: '가슴', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'c03', name: '디클라인 바벨 벤치프레스',  body_part: '가슴', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'c04', name: '클로즈그립 벤치프레스',     body_part: '가슴', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'c05', name: '랜드마인 체스트 프레스',    body_part: '가슴', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'c06', name: '덤벨 벤치프레스',           body_part: '가슴', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'c07', name: '인클라인 덤벨 벤치프레스',  body_part: '가슴', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'c08', name: '디클라인 덤벨 벤치프레스',  body_part: '가슴', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'c09', name: '덤벨 플라이',               body_part: '가슴', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'c10', name: '인클라인 덤벨 플라이',      body_part: '가슴', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'c11', name: '케이블 크로스오버',          body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c12', name: '로우 케이블 플라이',         body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c13', name: '하이 케이블 플라이',         body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c14', name: '펙덱 플라이',               body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c15', name: '체스트 프레스 머신',         body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c16', name: '스미스 머신 벤치프레스',     body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c17', name: '푸시업',                    body_part: '가슴', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'c18', name: '인클라인 푸시업',            body_part: '가슴', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'c19', name: '디클라인 푸시업',            body_part: '가슴', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'c20', name: '다이아몬드 푸시업',          body_part: '가슴', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'c21', name: '딥스',                      body_part: '가슴', equipment: '맨몸',  record_type: 'reps_only' },

  { id: 'c22', name: '스미스 머신 인클라인 벤치프레스', body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c23', name: '스미스 머신 디클라인 벤치프레스', body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c24', name: '인클라인 체스트 프레스 머신',   body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c25', name: '디클라인 체스트 프레스 머신',   body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c26', name: '플레이트 로드 체스트 프레스',   body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c27', name: '싱글암 체스트 프레스 머신',     body_part: '가슴', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'c28', name: '케이블 인클라인 플라이',        body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c29', name: '케이블 디클라인 플라이',        body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c30', name: '싱글암 케이블 플라이',          body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c31', name: '덤벨 스퀴즈 프레스',           body_part: '가슴', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'c32', name: '밴드 체스트 프레스',           body_part: '가슴', equipment: '밴드',  record_type: 'reps_only' },
  { id: 'c33', name: '밴드 플라이',                 body_part: '가슴', equipment: '밴드',  record_type: 'reps_only' },

  { id: 'c34', name: '리버스그립 바벨 벤치프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c35', name: '포즈 벤치프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c36', name: '템포 벤치프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c37', name: '라슨 프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c38', name: '바벨 플로어 프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c39', name: '스포토 프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c40', name: '와이드그립 벤치프레스', body_part: '가슴', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'c41', name: '덤벨 플로어 프레스', body_part: '가슴', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'c42', name: '뉴트럴그립 덤벨 벤치프레스', body_part: '가슴', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'c43', name: '싱글암 덤벨 벤치프레스', body_part: '가슴', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'c44', name: '덤벨 헥스 프레스', body_part: '가슴', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'c45', name: '덤벨 풀오버 체스트 포커스', body_part: '가슴', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'c46', name: '스탠딩 케이블 체스트 프레스', body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c47', name: '싱글암 케이블 체스트 프레스', body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c48', name: '로우투하이 케이블 플라이', body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c49', name: '하이투로우 케이블 플라이', body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c50', name: '미드 케이블 플라이', body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c51', name: '시티드 케이블 체스트 프레스', body_part: '가슴', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'c52', name: '컨버징 체스트 프레스 머신', body_part: '가슴', equipment: '머신', record_type: 'weight_reps' },
  { id: 'c53', name: '아이소레터럴 체스트 프레스', body_part: '가슴', equipment: '머신', record_type: 'weight_reps' },
  { id: 'c54', name: '해머스트렝스 인클라인 프레스', body_part: '가슴', equipment: '머신', record_type: 'weight_reps' },
  { id: 'c55', name: '해머스트렝스 디클라인 프레스', body_part: '가슴', equipment: '머신', record_type: 'weight_reps' },
  { id: 'c56', name: '니링 푸시업', body_part: '가슴', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'c57', name: '아처 푸시업', body_part: '가슴', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'c58', name: '플라이오메트릭 푸시업', body_part: '가슴', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'c59', name: '링 푸시업', body_part: '가슴', equipment: '기타', record_type: 'reps_only' },
  { id: 'c60', name: '링 딥스', body_part: '가슴', equipment: '기타', record_type: 'reps_only' },
  { id: 'c61', name: '웨이티드 딥스', body_part: '가슴', equipment: '기타', record_type: 'weight_reps' },

  // ── 등 ───────────────────────────────────────────────────────────────────
  { id: 'b01', name: '바벨 데드리프트',           body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b02', name: '루마니안 데드리프트',        body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b03', name: '스모 데드리프트',            body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b04', name: '바벨 로우',                 body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b05', name: '펜들레이 로우',              body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b06', name: '티바 로우',                 body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b07', name: '랙풀',                      body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b08', name: '덤벨 로우',                 body_part: '등', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'b09', name: '덤벨 풀오버',               body_part: '등', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'b10', name: '랫풀다운',                  body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b11', name: '리버스그립 랫풀다운',        body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b12', name: '시티드 케이블 로우',         body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b13', name: '스트레이트암 풀다운',         body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b14', name: '싱글암 케이블 로우',          body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b15', name: '케이블 풀오버',              body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b16', name: '케이블 Y 레이즈',            body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b17', name: '머신 로우',                 body_part: '등', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'b18', name: '풀업',                      body_part: '등', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'b19', name: '친업',                      body_part: '등', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'b20', name: '인버티드 로우',              body_part: '등', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'b21', name: '하이퍼익스텐션',             body_part: '등', equipment: '맨몸',  record_type: 'reps_only' },

  { id: 'b22', name: '체스트 서포티드 덤벨 로우',      body_part: '등', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'b23', name: '씰 로우',                      body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b24', name: '와이드그립 랫풀다운',           body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b25', name: '뉴트럴그립 랫풀다운',          body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b26', name: '클로즈그립 랫풀다운',          body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b27', name: '싱글암 랫풀다운',              body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b28', name: '체스트 서포티드 머신 로우',     body_part: '등', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'b29', name: '하이 로우 머신',               body_part: '등', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'b30', name: '로우 로우 머신',               body_part: '등', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'b31', name: '어시스트 풀업 머신',           body_part: '등', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'b32', name: '웨이티드 풀업',                body_part: '등', equipment: '기타',  record_type: 'weight_reps' },
  { id: 'b33', name: '메도우 로우',                  body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b34', name: '원암 랜드마인 로우',           body_part: '등', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'b35', name: '케틀벨 원암 로우',             body_part: '등', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'b36', name: '밴드 랫풀다운',                body_part: '등', equipment: '밴드',  record_type: 'reps_only' },
  { id: 'b37', name: '밴드 시티드 로우',             body_part: '등', equipment: '밴드',  record_type: 'reps_only' },

  { id: 'b38', name: '언더핸드 바벨 로우', body_part: '등', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'b39', name: '와이드그립 바벨 로우', body_part: '등', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'b40', name: '스내치그립 바벨 로우', body_part: '등', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'b41', name: '헬름스 로우', body_part: '등', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'b42', name: '랜드마인 티바 로우', body_part: '등', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'b43', name: '체스트 서포티드 바벨 로우', body_part: '등', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'b44', name: '싱글암 덤벨 벤치 로우', body_part: '등', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'b45', name: '인클라인 벤치 덤벨 로우', body_part: '등', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'b46', name: '덤벨 고릴라 로우', body_part: '등', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'b47', name: '레니게이드 로우', body_part: '등', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'b48', name: '덤벨 데드스톱 로우', body_part: '등', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'b49', name: '와이드그립 시티드 케이블 로우', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b50', name: '클로즈그립 시티드 케이블 로우', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b51', name: '뉴트럴그립 시티드 케이블 로우', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b52', name: '언더핸드 시티드 케이블 로우', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b53', name: '하이 케이블 로우', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b54', name: '니링 싱글암 랫풀다운', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b55', name: '와이드 뉴트럴 랫풀다운', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b56', name: 'V바 랫풀다운', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b57', name: '비하인드넥 랫풀다운', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b58', name: '로프 스트레이트암 풀다운', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b59', name: '싱글암 스트레이트암 풀다운', body_part: '등', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'b60', name: '플레이트 로드 로우', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b61', name: '아이소레터럴 로우 머신', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b62', name: '와이드그립 머신 로우', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b63', name: '언더핸드 머신 로우', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b64', name: '풀오버 머신', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b65', name: '랫풀다운 머신', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b66', name: '아이소레터럴 랫풀다운 머신', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b67', name: '머신 하이 로우 싱글암', body_part: '등', equipment: '머신', record_type: 'weight_reps' },
  { id: 'b68', name: '스캡 풀업', body_part: '등', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'b69', name: '아처 풀업', body_part: '등', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'b70', name: '뉴트럴그립 풀업', body_part: '등', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'b71', name: '와이드그립 풀업', body_part: '등', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'b72', name: '타월 풀업', body_part: '등', equipment: '기타', record_type: 'reps_only' },
  { id: 'b73', name: '웨이티드 친업', body_part: '등', equipment: '기타', record_type: 'weight_reps' },
  { id: 'b74', name: '링 로우', body_part: '등', equipment: '기타', record_type: 'reps_only' },
  { id: 'b75', name: '링 풀업', body_part: '등', equipment: '기타', record_type: 'reps_only' },

  // ── 어깨 ─────────────────────────────────────────────────────────────────
  { id: 's01', name: '바벨 오버헤드 프레스',       body_part: '어깨', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 's02', name: '바벨 업라이트 로우',          body_part: '어깨', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 's03', name: '바벨 쉬러그',               body_part: '어깨', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 's04', name: '랜드마인 프레스',             body_part: '어깨', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 's05', name: '덤벨 오버헤드 프레스',        body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's06', name: '아놀드 프레스',              body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's07', name: '덤벨 레터럴 레이즈',          body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's08', name: '덤벨 프론트 레이즈',          body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's09', name: '리어 델트 덤벨 플라이',       body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's10', name: '덤벨 쉬러그',               body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's11', name: '케이블 레터럴 레이즈',        body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's12', name: '케이블 프론트 레이즈',        body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's13', name: '케이블 페이스 풀',            body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's14', name: '숄더 프레스 머신',            body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's15', name: '머신 레터럴 레이즈',          body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's16', name: '리어 델트 머신',             body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's17', name: '파이크 푸시업',              body_part: '어깨', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 's18', name: '핸드스탠드 푸시업',           body_part: '어깨', equipment: '맨몸',  record_type: 'reps_only' },

  { id: 's19', name: '스미스 머신 숄더 프레스',      body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's20', name: '머신 오버헤드 프레스',          body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's21', name: '싱글암 머신 숄더 프레스',       body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's22', name: '리닝 케이블 레터럴 레이즈',     body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's23', name: '비하인드백 케이블 레터럴 레이즈', body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's24', name: '케이블 리어 델트 플라이',       body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's25', name: '리버스 펙덱',                  body_part: '어깨', equipment: '머신',  record_type: 'weight_reps' },
  { id: 's26', name: '덤벨 Y 레이즈',                body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's27', name: '인클라인 덤벨 레터럴 레이즈',    body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's28', name: '덤벨 리어 델트 로우',           body_part: '어깨', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 's29', name: '케틀벨 숄더 프레스',            body_part: '어깨', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 's30', name: '케틀벨 푸시 프레스',            body_part: '어깨', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 's31', name: '밴드 페이스 풀',               body_part: '어깨', equipment: '밴드',  record_type: 'reps_only' },
  { id: 's32', name: '밴드 풀어파트',                body_part: '어깨', equipment: '밴드',  record_type: 'reps_only' },
  { id: 's33', name: '밴드 레터럴 레이즈',           body_part: '어깨', equipment: '밴드',  record_type: 'reps_only' },

  { id: 's34', name: '바벨 푸시 프레스', body_part: '어깨', equipment: '바벨', record_type: 'weight_reps' },
  { id: 's35', name: '비하인드넥 프레스', body_part: '어깨', equipment: '바벨', record_type: 'weight_reps' },
  { id: 's36', name: '브래드포드 프레스', body_part: '어깨', equipment: '바벨', record_type: 'weight_reps' },
  { id: 's37', name: '시티드 바벨 오버헤드 프레스', body_part: '어깨', equipment: '바벨', record_type: 'weight_reps' },
  { id: 's38', name: '싱글암 랜드마인 프레스', body_part: '어깨', equipment: '바벨', record_type: 'weight_reps' },
  { id: 's39', name: '하프니링 랜드마인 프레스', body_part: '어깨', equipment: '바벨', record_type: 'weight_reps' },
  { id: 's40', name: '시티드 덤벨 숄더 프레스', body_part: '어깨', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 's41', name: '싱글암 덤벨 숄더 프레스', body_part: '어깨', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 's42', name: '덤벨 푸시 프레스', body_part: '어깨', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 's43', name: '덤벨 스카프션 레이즈', body_part: '어깨', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 's44', name: '덤벨 45도 레터럴 레이즈', body_part: '어깨', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 's45', name: '체스트 서포티드 리어 델트 레이즈', body_part: '어깨', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 's46', name: '프론트 케이블 레터럴 레이즈', body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's47', name: '크로스바디 케이블 레터럴 레이즈', body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's48', name: '케이블 업라이트 로우', body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's49', name: '케이블 Y 프레스', body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's50', name: '싱글암 케이블 리어 델트 플라이', body_part: '어깨', equipment: '케이블', record_type: 'weight_reps' },
  { id: 's51', name: '플레이트 프론트 레이즈', body_part: '어깨', equipment: '기타', record_type: 'weight_reps' },
  { id: 's52', name: '플레이트 스티어링 휠', body_part: '어깨', equipment: '기타', record_type: 'weight_reps' },
  { id: 's53', name: '해머스트렝스 숄더 프레스', body_part: '어깨', equipment: '머신', record_type: 'weight_reps' },
  { id: 's54', name: '컨버징 숄더 프레스 머신', body_part: '어깨', equipment: '머신', record_type: 'weight_reps' },
  { id: 's55', name: '리어 델트 로우 머신', body_part: '어깨', equipment: '머신', record_type: 'weight_reps' },
  { id: 's56', name: '케틀벨 아놀드 프레스', body_part: '어깨', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 's57', name: '케틀벨 보텀업 프레스', body_part: '어깨', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 's58', name: '밴드 외회전', body_part: '어깨', equipment: '밴드', record_type: 'reps_only' },
  { id: 's59', name: '밴드 내회전', body_part: '어깨', equipment: '밴드', record_type: 'reps_only' },
  { id: 's60', name: '월 핸드스탠드 홀드', body_part: '어깨', equipment: '맨몸', record_type: 'time' },

  // ── 삼두 ─────────────────────────────────────────────────────────────────
  { id: 't01', name: '스컬크러셔',                body_part: '삼두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 't02', name: 'JM 프레스',                body_part: '삼두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 't03', name: '덤벨 오버헤드 트라이셉스 익스텐션', body_part: '삼두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 't04', name: '덤벨 킥백',                body_part: '삼두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 't05', name: '덤벨 스컬크러셔',           body_part: '삼두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 't06', name: '케이블 트라이셉스 푸시다운', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't07', name: '케이블 로프 푸시다운',       body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't08', name: '케이블 오버헤드 트라이셉스 익스텐션', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't09', name: '리버스그립 케이블 푸시다운', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't10', name: '케이블 크로스바디 익스텐션', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't11', name: '머신 트라이셉스 익스텐션',   body_part: '삼두', equipment: '머신',  record_type: 'weight_reps' },
  { id: 't12', name: '트라이셉스 딥스',            body_part: '삼두', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 't13', name: '벤치 딥스',                body_part: '삼두', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 't14', name: '클로즈그립 푸시업',          body_part: '삼두', equipment: '맨몸',  record_type: 'reps_only' },

  { id: 't15', name: '싱글암 케이블 푸시다운',        body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't16', name: '싱글암 오버헤드 케이블 익스텐션', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't17', name: 'EZ바 스컬크러셔',              body_part: '삼두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 't18', name: '클로즈그립 바벨 벤치프레스',    body_part: '삼두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 't19', name: '머신 딥스',                    body_part: '삼두', equipment: '머신',  record_type: 'weight_reps' },
  { id: 't20', name: '어시스트 딥스 머신',           body_part: '삼두', equipment: '머신',  record_type: 'weight_reps' },
  { id: 't21', name: '케이블 킥백',                  body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't22', name: '밴드 푸시다운',                body_part: '삼두', equipment: '밴드',  record_type: 'reps_only' },
  { id: 't23', name: '밴드 오버헤드 트라이셉스 익스텐션', body_part: '삼두', equipment: '밴드', record_type: 'reps_only' },

  { id: 't24', name: '바벨 롤링 트라이셉스 익스텐션', body_part: '삼두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 't25', name: 'EZ바 오버헤드 트라이셉스 익스텐션', body_part: '삼두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 't26', name: '클로즈그립 스미스 벤치프레스', body_part: '삼두', equipment: '머신', record_type: 'weight_reps' },
  { id: 't27', name: '스미스 JM 프레스', body_part: '삼두', equipment: '머신', record_type: 'weight_reps' },
  { id: 't28', name: '덤벨 테이트 프레스', body_part: '삼두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 't29', name: '덤벨 롤링 트라이셉스 익스텐션', body_part: '삼두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 't30', name: '싱글암 덤벨 오버헤드 익스텐션', body_part: '삼두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 't31', name: '크로스바디 덤벨 익스텐션', body_part: '삼두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 't32', name: '스트레이트바 케이블 푸시다운', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't33', name: 'V바 케이블 푸시다운', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't34', name: '언더핸드 싱글암 푸시다운', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't35', name: '듀얼 케이블 오버헤드 익스텐션', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't36', name: '케이블 스컬크러셔', body_part: '삼두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 't37', name: '트라이셉스 프레스 머신', body_part: '삼두', equipment: '머신', record_type: 'weight_reps' },
  { id: 't38', name: '웨이티드 벤치 딥스', body_part: '삼두', equipment: '기타', record_type: 'weight_reps' },
  { id: 't39', name: '웨이티드 트라이셉스 딥스', body_part: '삼두', equipment: '기타', record_type: 'weight_reps' },
  { id: 't40', name: '링 트라이셉스 익스텐션', body_part: '삼두', equipment: '기타', record_type: 'reps_only' },
  { id: 't41', name: '바디웨이트 트라이셉스 익스텐션', body_part: '삼두', equipment: '맨몸', record_type: 'reps_only' },

  // ── 이두 ─────────────────────────────────────────────────────────────────
  { id: 'bi01', name: '바벨 컬',                 body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi02', name: 'EZ바 컬',                body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi03', name: '프리처 컬',               body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi04', name: '스파이더 컬',              body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi05', name: '리버스 바벨 컬',           body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi06', name: '바벨 21s',               body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi07', name: '덤벨 컬',                 body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi08', name: '해머 컬',                 body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi09', name: '인클라인 덤벨 컬',         body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi10', name: '컨센트레이션 컬',          body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi11', name: '크로스 바디 해머 컬',      body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi12', name: '케이블 컬',               body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi13', name: '케이블 해머 컬',           body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi14', name: '리버스 케이블 컬',         body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi15', name: '머신 컬',                 body_part: '이두', equipment: '머신',  record_type: 'weight_reps' },

  { id: 'bi16', name: 'EZ바 프리처 컬',             body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi17', name: '덤벨 프리처 컬',              body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi18', name: '해머 프리처 컬',              body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi19', name: '베이지안 케이블 컬',           body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi20', name: '싱글암 케이블 컬',             body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi21', name: '하이 케이블 컬',               body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi22', name: '드래그 컬',                    body_part: '이두', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'bi23', name: '조트맨 컬',                    body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi24', name: '리버스 덤벨 컬',               body_part: '이두', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'bi25', name: '밴드 바이셉스 컬',             body_part: '이두', equipment: '밴드',  record_type: 'reps_only' },

  { id: 'bi26', name: '와이드그립 바벨 컬', body_part: '이두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'bi27', name: '클로즈그립 바벨 컬', body_part: '이두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'bi28', name: '시티드 바벨 컬', body_part: '이두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'bi29', name: 'EZ바 리버스 컬', body_part: '이두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'bi30', name: 'EZ바 스파이더 컬', body_part: '이두', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'bi31', name: '얼터네이팅 덤벨 컬', body_part: '이두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'bi32', name: '시티드 덤벨 컬', body_part: '이두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'bi33', name: '인클라인 해머 컬', body_part: '이두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'bi34', name: '스파이더 덤벨 컬', body_part: '이두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'bi35', name: '드래그 덤벨 컬', body_part: '이두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'bi36', name: '프로나티드 덤벨 컬', body_part: '이두', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'bi37', name: '라잉 케이블 컬', body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi38', name: '로우 케이블 컬', body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi39', name: '프리처 케이블 컬', body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi40', name: '로프 케이블 컬', body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi41', name: '듀얼 케이블 바이셉스 컬', body_part: '이두', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'bi42', name: '머신 프리처 컬', body_part: '이두', equipment: '머신', record_type: 'weight_reps' },
  { id: 'bi43', name: '싱글암 머신 컬', body_part: '이두', equipment: '머신', record_type: 'weight_reps' },
  { id: 'bi44', name: '케틀벨 컬', body_part: '이두', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'bi45', name: '케틀벨 해머 컬', body_part: '이두', equipment: '케틀벨', record_type: 'weight_reps' },

  // ── 하체 ─────────────────────────────────────────────────────────────────
  { id: 'l01', name: '바벨 백스쿼트',            body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l02', name: '바벨 프론트스쿼트',         body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l03', name: '힙 쓰러스트',              body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l04', name: '바벨 루마니안 데드리프트',   body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l05', name: '고블렛 스쿼트',            body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l06', name: '불가리안 스플릿 스쿼트',    body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l07', name: '덤벨 런지',               body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l08', name: '워킹 런지',               body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l09', name: '덤벨 스텝업',             body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l10', name: '싱글레그 데드리프트',       body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l11', name: '스모 덤벨 스쿼트',         body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l12', name: '케틀벨 스윙',             body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l13', name: '레그 프레스',             body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l14', name: '레그 익스텐션',            body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l15', name: '라잉 레그 컬',            body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l16', name: '시티드 레그 컬',           body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l17', name: '스탠딩 카프 레이즈',        body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l18', name: '시티드 카프 레이즈',        body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l19', name: '해크 스쿼트',             body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l20', name: '스미스 머신 스쿼트',        body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l21', name: '레그 애브덕션',            body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l22', name: '레그 애덕션',             body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l23', name: '글루트 브리지',            body_part: '하체', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'l24', name: '박스 점프',               body_part: '하체', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'l25', name: '점프 스쿼트',             body_part: '하체', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'l26', name: '월 싯',                  body_part: '하체', equipment: '맨몸',  record_type: 'time' },

  { id: 'l27', name: '펜듈럼 스쿼트',               body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l28', name: '브이 스쿼트',                  body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l29', name: '벨트 스쿼트',                  body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l30', name: '스미스 머신 런지',             body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l31', name: '스미스 불가리안 스플릿 스쿼트', body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l32', name: '스미스 머신 힙 쓰러스트',       body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l33', name: '바벨 런지',                    body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l34', name: '바벨 스플릿 스쿼트',            body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l35', name: '스티프레그 데드리프트',         body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l36', name: '바벨 굿모닝',                  body_part: '하체', equipment: '바벨',  record_type: 'weight_reps' },
  { id: 'l37', name: '덤벨 루마니안 데드리프트',      body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l38', name: '덤벨 리버스 런지',             body_part: '하체', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'l39', name: '싱글레그 레그 프레스',          body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l40', name: '수평 레그 프레스',             body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l41', name: '글루트 킥백 머신',             body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l42', name: '케이블 글루트 킥백',           body_part: '하체', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'l43', name: '케이블 힙 어브덕션',           body_part: '하체', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'l44', name: '케이블 힙 어덕션',             body_part: '하체', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'l45', name: '노르딕 햄스트링 컬',           body_part: '하체', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'l46', name: '리버스 노르딕',                body_part: '하체', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'l47', name: '싱글레그 카프 레이즈',          body_part: '하체', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'l48', name: '돈키 카프 레이즈 머신',         body_part: '하체', equipment: '머신',  record_type: 'weight_reps' },
  { id: 'l49', name: '케틀벨 고블렛 스쿼트',          body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l50', name: '케틀벨 데드리프트',            body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l51', name: '케틀벨 리버스 런지',           body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l52', name: '밴드 스쿼트',                  body_part: '하체', equipment: '밴드',  record_type: 'reps_only' },
  { id: 'l53', name: '밴드 레터럴 워크',             body_part: '하체', equipment: '밴드',  record_type: 'reps_only' },
  { id: 'l54', name: '밴드 글루트 브리지',           body_part: '하체', equipment: '밴드',  record_type: 'reps_only' },

  { id: 'l55', name: '하이바 백스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l56', name: '로우바 백스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l57', name: '포즈 백스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l58', name: '템포 백스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l59', name: '박스 스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l60', name: '제처 스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l61', name: '오버헤드 스쿼트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l62', name: '핵 스쿼트 바벨', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l63', name: '바벨 리버스 런지', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l64', name: '바벨 워킹 런지', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l65', name: '바벨 스텝업', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l66', name: '싱글레그 바벨 RDL', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l67', name: '스내치그립 루마니안 데드리프트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l68', name: '데피싯 루마니안 데드리프트', body_part: '하체', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'l69', name: '덤벨 프론트 스쿼트', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l70', name: '덤벨 스플릿 스쿼트', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l71', name: '덤벨 사이드 런지', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l72', name: '덤벨 커시 런지', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l73', name: '덤벨 불가리안 스플릿 스쿼트', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l74', name: '덤벨 힙 쓰러스트', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l75', name: '덤벨 글루트 브리지', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l76', name: '싱글레그 덤벨 RDL', body_part: '하체', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'l77', name: '45도 레그 프레스', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l78', name: '와이드 스탠스 레그 프레스', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l79', name: '내로우 스탠스 레그 프레스', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l80', name: '하이풋 레그 프레스', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l81', name: '로우풋 레그 프레스', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l82', name: '싱글레그 레그 익스텐션', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l83', name: '싱글레그 라잉 레그 컬', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l84', name: '싱글레그 시티드 레그 컬', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l85', name: '스탠딩 싱글레그 컬 머신', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l86', name: '글루트 햄 레이즈 머신', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l87', name: '리버스 하이퍼 머신', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l88', name: '스미스 머신 RDL', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l89', name: '스미스 머신 굿모닝', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l90', name: '스미스 머신 카프 레이즈', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l91', name: '레그 프레스 카프 레이즈', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l92', name: '핵스쿼트 카프 레이즈', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l93', name: '힙 쓰러스트 머신', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l94', name: '글루트 드라이브 머신', body_part: '하체', equipment: '머신', record_type: 'weight_reps' },
  { id: 'l95', name: '싱글레그 힙 쓰러스트', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l96', name: '리버스 런지', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l97', name: '사이드 런지', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l98', name: '커시 런지', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l99', name: '스플릿 스쿼트', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l100', name: '피스톨 스쿼트', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l101', name: '코사크 스쿼트', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l102', name: '싱글레그 글루트 브리지', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l103', name: '프로그 펌프', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l104', name: '리버스 하이퍼 바디웨이트', body_part: '하체', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'l105', name: '케틀벨 프론트 스쿼트', body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l106', name: '더블 케틀벨 프론트 스쿼트', body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l107', name: '케틀벨 불가리안 스플릿 스쿼트', body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l108', name: '케틀벨 싱글레그 RDL', body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l109', name: '케틀벨 스모 데드리프트', body_part: '하체', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'l110', name: '밴드 힙 어브덕션', body_part: '하체', equipment: '밴드', record_type: 'reps_only' },
  { id: 'l111', name: '밴드 힙 어덕션', body_part: '하체', equipment: '밴드', record_type: 'reps_only' },
  { id: 'l112', name: '밴드 킥백', body_part: '하체', equipment: '밴드', record_type: 'reps_only' },
  { id: 'l113', name: '밴드 몬스터 워크', body_part: '하체', equipment: '밴드', record_type: 'reps_only' },
  { id: 'l114', name: '밴드 클램셸', body_part: '하체', equipment: '밴드', record_type: 'reps_only' },

  // ── 복근 ─────────────────────────────────────────────────────────────────
  { id: 'ab01', name: '크런치',                 body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab02', name: '싯업',                   body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab03', name: '레그레이즈',              body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab04', name: '행잉 레그레이즈',          body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab05', name: '행잉 니레이즈',            body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab06', name: '플랭크',                  body_part: '복근', equipment: '맨몸',  record_type: 'time' },
  { id: 'ab07', name: '사이드 플랭크',            body_part: '복근', equipment: '맨몸',  record_type: 'time' },
  { id: 'ab08', name: '마운틴 클라이머',          body_part: '복근', equipment: '맨몸',  record_type: 'time' },
  { id: 'ab09', name: 'AB 롤아웃',              body_part: '복근', equipment: '기타',  record_type: 'reps_only' },
  { id: 'ab10', name: '러시안 트위스트',          body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab11', name: 'V업',                    body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab12', name: '바이시클 크런치',          body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab13', name: '토 투 바',               body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab14', name: '윈드실드 와이퍼',          body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab15', name: '드래곤 플래그',            body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab16', name: '케이블 크런치',            body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab17', name: '케이블 우드찹',            body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab18', name: '덤벨 사이드 벤드',         body_part: '복근', equipment: '덤벨',  record_type: 'weight_reps' },

  { id: 'ab19', name: '데드 버그',                  body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab20', name: '버드독',                     body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab21', name: '할로우 바디 홀드',            body_part: '복근', equipment: '맨몸',  record_type: 'time' },
  { id: 'ab22', name: '리버스 크런치',               body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab23', name: '디클라인 싯업',               body_part: '복근', equipment: '맨몸',  record_type: 'reps_only' },
  { id: 'ab24', name: '캡틴체어 니레이즈',           body_part: '복근', equipment: '머신',  record_type: 'reps_only' },
  { id: 'ab25', name: '웨이티드 크런치',             body_part: '복근', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'ab26', name: '웨이티드 싯업',               body_part: '복근', equipment: '덤벨',  record_type: 'weight_reps' },
  { id: 'ab27', name: '팔로프 프레스',               body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab28', name: '케이블 니링 크런치',           body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab29', name: '메디신볼 러시안 트위스트',     body_part: '복근', equipment: '기타',  record_type: 'weight_reps' },
  { id: 'ab30', name: '케틀벨 윈드밀',               body_part: '복근', equipment: '케틀벨', record_type: 'weight_reps' },

  { id: 'ab31', name: '머신 크런치', body_part: '복근', equipment: '머신', record_type: 'weight_reps' },
  { id: 'ab32', name: '토르소 로테이션 머신', body_part: '복근', equipment: '머신', record_type: 'weight_reps' },
  { id: 'ab33', name: '앱 코스터', body_part: '복근', equipment: '머신', record_type: 'reps_only' },
  { id: 'ab34', name: '행잉 오블리크 니레이즈', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab35', name: '행잉 윈드실드 와이퍼', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab36', name: '리버스 크런치 벤치', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab37', name: '잭나이프 싯업', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab38', name: '플러터 킥', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab39', name: '시저 킥', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab40', name: '홀로우 락', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab41', name: '플랭크 숄더 탭', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab42', name: '플랭크 잭', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab43', name: 'RKC 플랭크', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab44', name: '롱레버 플랭크', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab45', name: '코펜하겐 플랭크', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab46', name: '베어 플랭크', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab47', name: '슈퍼맨 홀드', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab48', name: '슈퍼맨', body_part: '복근', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ab49', name: '리버스 플랭크', body_part: '복근', equipment: '맨몸', record_type: 'time' },
  { id: 'ab50', name: '케이블 리버스 크런치', body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab51', name: '스탠딩 케이블 크런치', body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab52', name: '싱글암 케이블 사이드 벤드', body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab53', name: '하프니링 팔로프 프레스', body_part: '복근', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'ab54', name: '팔로프 프레스 홀드', body_part: '복근', equipment: '케이블', record_type: 'time' },
  { id: 'ab55', name: '랜드마인 로테이션', body_part: '복근', equipment: '바벨', record_type: 'weight_reps' },

  // ── 유산소 ───────────────────────────────────────────────────────────────
  { id: 'ca01', name: '트레드밀 달리기',           body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca02', name: '실내 사이클',              body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca03', name: '일립티컬',                body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca04', name: '로잉 머신',               body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca05', name: '스테어 클라이머',           body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca06', name: '어시트 바이크',             body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca07', name: '스키 에르그',              body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca08', name: '줄넘기',                  body_part: '유산소', equipment: '기타', record_type: 'time' },
  { id: 'ca09', name: '버피',                    body_part: '유산소', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ca10', name: '점핑잭',                  body_part: '유산소', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ca11', name: '배틀 로프',               body_part: '유산소', equipment: '기타', record_type: 'time' },
  { id: 'ca12', name: '하이 니',                 body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca13', name: '야외 달리기',              body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca14', name: '수영',                    body_part: '유산소', equipment: '기타', record_type: 'time' },
  { id: 'ca15', name: '스프린트',                body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca16', name: '트레드밀 걷기',               body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca17', name: '인클라인 트레드밀 걷기',       body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca18', name: '스핀 바이크',                  body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca19', name: '에어 바이크',                  body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca20', name: '셔틀런',                      body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca21', name: '계단 오르기',                  body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca22', name: '제자리 달리기',                body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca23', name: '섀도 복싱',                    body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca24', name: '복싱 샌드백',                  body_part: '유산소', equipment: '기타', record_type: 'time' },
  { id: 'ca25', name: '썰매 밀기',                    body_part: '유산소', equipment: '기타', record_type: 'time' },
  { id: 'ca26', name: '썰매 당기기',                  body_part: '유산소', equipment: '기타', record_type: 'time' },


  { id: 'ca27', name: '트레드밀 인터벌', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca28', name: '트레드밀 경사 인터벌', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca29', name: '사이클 인터벌', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca30', name: '로잉 인터벌', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca31', name: '스키 에르그 인터벌', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca32', name: '에어 바이크 인터벌', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca33', name: '스텝밀', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca34', name: '아크 트레이너', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca35', name: '크로스트레이너', body_part: '유산소', equipment: '머신', record_type: 'time' },
  { id: 'ca36', name: '파머스 워크', body_part: '유산소', equipment: '덤벨', record_type: 'time' },
  { id: 'ca37', name: '수트케이스 캐리', body_part: '유산소', equipment: '덤벨', record_type: 'time' },
  { id: 'ca38', name: '오버헤드 캐리', body_part: '유산소', equipment: '덤벨', record_type: 'time' },
  { id: 'ca39', name: '케틀벨 파머스 워크', body_part: '유산소', equipment: '케틀벨', record_type: 'time' },
  { id: 'ca40', name: '케틀벨 수트케이스 캐리', body_part: '유산소', equipment: '케틀벨', record_type: 'time' },
  { id: 'ca41', name: '케틀벨 랙 캐리', body_part: '유산소', equipment: '케틀벨', record_type: 'time' },
  { id: 'ca42', name: '샌드백 캐리', body_part: '유산소', equipment: '기타', record_type: 'time' },
  { id: 'ca43', name: '베어 크롤', body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca44', name: '크랩 워크', body_part: '유산소', equipment: '맨몸', record_type: 'time' },
  { id: 'ca45', name: '스케이터 점프', body_part: '유산소', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ca46', name: '브로드 점프', body_part: '유산소', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ca47', name: '박스 스텝오버', body_part: '유산소', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'ca48', name: '사이드 셔플', body_part: '유산소', equipment: '맨몸', record_type: 'time' },

  // ── 전완 ─────────────────────────────────────────────────────────────────
  { id: 'f01', name: '바벨 리스트 컬', body_part: '전완', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'f02', name: '리버스 바벨 리스트 컬', body_part: '전완', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'f03', name: '비하인드백 바벨 리스트 컬', body_part: '전완', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'f04', name: '덤벨 리스트 컬', body_part: '전완', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'f05', name: '리버스 덤벨 리스트 컬', body_part: '전완', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'f06', name: '덤벨 손목 회전', body_part: '전완', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'f07', name: '케이블 리스트 컬', body_part: '전완', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'f08', name: '리버스 케이블 리스트 컬', body_part: '전완', equipment: '케이블', record_type: 'weight_reps' },
  { id: 'f09', name: '리스트 롤러', body_part: '전완', equipment: '기타', record_type: 'reps_only' },
  { id: 'f10', name: '플레이트 핀치 홀드', body_part: '전완', equipment: '기타', record_type: 'time' },
  { id: 'f11', name: '플레이트 핀치 캐리', body_part: '전완', equipment: '기타', record_type: 'time' },
  { id: 'f12', name: '데드 행', body_part: '전완', equipment: '맨몸', record_type: 'time' },
  { id: 'f13', name: '타월 데드 행', body_part: '전완', equipment: '기타', record_type: 'time' },
  { id: 'f14', name: '원암 데드 행', body_part: '전완', equipment: '맨몸', record_type: 'time' },
  { id: 'f15', name: '행잉 스캡 홀드', body_part: '전완', equipment: '맨몸', record_type: 'time' },
  { id: 'f16', name: '핸드 그리퍼', body_part: '전완', equipment: '기타', record_type: 'reps_only' },
  { id: 'f17', name: '파머스 홀드', body_part: '전완', equipment: '덤벨', record_type: 'time' },
  { id: 'f18', name: '바벨 홀드', body_part: '전완', equipment: '바벨', record_type: 'time' },
  { id: 'f19', name: '케틀벨 홀드', body_part: '전완', equipment: '케틀벨', record_type: 'time' },
  { id: 'f20', name: '핑거 컬', body_part: '전완', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'f21', name: '덤벨 리버스 컬 전완 포커스', body_part: '전완', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'f22', name: '밴드 리스트 컬', body_part: '전완', equipment: '밴드', record_type: 'reps_only' },
  { id: 'f23', name: '밴드 손목 회전', body_part: '전완', equipment: '밴드', record_type: 'reps_only' },
  { id: 'f24', name: '라이스 버킷 손목 운동', body_part: '전완', equipment: '기타', record_type: 'time' },

  // ── 전신 ─────────────────────────────────────────────────────────────────
  { id: 'fb01', name: '바벨 클린', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb02', name: '파워 클린', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb03', name: '행 클린', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb04', name: '클린 앤 저크', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb05', name: '바벨 스내치', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb06', name: '파워 스내치', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb07', name: '행 스내치', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb08', name: '클린 풀', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb09', name: '스내치 풀', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb10', name: '바벨 스러스터', body_part: '전신', equipment: '바벨', record_type: 'weight_reps' },
  { id: 'fb11', name: '덤벨 스러스터', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb12', name: '덤벨 클린', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb13', name: '덤벨 파워 클린', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb14', name: '덤벨 클린 앤 프레스', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb15', name: '덤벨 스내치', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb16', name: '싱글암 덤벨 스내치', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb17', name: '덤벨 데빌 프레스', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb18', name: '덤벨 맨메이커', body_part: '전신', equipment: '덤벨', record_type: 'weight_reps' },
  { id: 'fb19', name: '케틀벨 클린', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb20', name: '케틀벨 클린 앤 프레스', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb21', name: '케틀벨 스내치', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb22', name: '케틀벨 하이풀', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb23', name: '케틀벨 터키시 겟업', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb24', name: '더블 케틀벨 클린', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb25', name: '더블 케틀벨 클린 앤 프레스', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb26', name: '케틀벨 롱 사이클', body_part: '전신', equipment: '케틀벨', record_type: 'weight_reps' },
  { id: 'fb27', name: '버피 풀업', body_part: '전신', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'fb28', name: '버피 박스 점프', body_part: '전신', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'fb29', name: '인치웜', body_part: '전신', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'fb30', name: '베어 크롤 푸시업', body_part: '전신', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'fb31', name: '마운틴 클라이머 푸시업', body_part: '전신', equipment: '맨몸', record_type: 'reps_only' },
  { id: 'fb32', name: '샌드백 클린', body_part: '전신', equipment: '기타', record_type: 'weight_reps' },
  { id: 'fb33', name: '샌드백 숄더링', body_part: '전신', equipment: '기타', record_type: 'weight_reps' },
  { id: 'fb34', name: '샌드백 스쿼트 투 프레스', body_part: '전신', equipment: '기타', record_type: 'weight_reps' },
  { id: 'fb35', name: '메디신볼 슬램', body_part: '전신', equipment: '기타', record_type: 'reps_only' },
  { id: 'fb36', name: '메디신볼 오버헤드 스로우', body_part: '전신', equipment: '기타', record_type: 'reps_only' },
  { id: 'fb37', name: '월볼 샷', body_part: '전신', equipment: '기타', record_type: 'reps_only' },
  { id: 'fb38', name: '배틀로프 버피', body_part: '전신', equipment: '기타', record_type: 'reps_only' },
];

// ── Helpers ────────────────────────────────────────────────────────────────

export function searchExercises(
  query: string,
  bodyPart?: BodyPart | null,
  equipment?: Equipment | null,
): Exercise[] {
  const q = query.trim().toLowerCase();
  return EXERCISE_DB.filter((ex) => {
    if (bodyPart && ex.body_part !== bodyPart) return false;
    if (equipment && ex.equipment !== equipment) return false;
    if (q && !ex.name.toLowerCase().includes(q)) return false;
    return true;
  });
}

export function findExerciseByName(name: string): Exercise | undefined {
  return EXERCISE_DB.find((ex) => ex.name === name);
}

export const BODY_PARTS: BodyPart[] = ['가슴', '등', '어깨', '삼두', '이두', '하체', '복근', '전완', '전신', '유산소'];
export const EQUIPMENTS: Equipment[] = ['맨몸', '덤벨', '바벨', '머신', '케이블', '케틀벨', '밴드', '기타'];

export const RECORD_TYPE_LABEL: Record<RecordType, string> = {
  weight_reps: '무게+횟수',
  reps_only:   '횟수',
  time:        '시간',
};
